### Recuperar todas las películas

GET http://localhost:3001/movies

### Recuperar película por nombre

GET http://localhost:3001/movies?Title=Star

### Recuperar una película
GET http://localhost:3001/movies/2

### Recuperar películas por género

GET http://localhost:3001/movies/genre/Horror

### Crear una película

POST http://localhost:3001/movies

Content-Type: application/json

  {
	 	"title": "Gato con Botas",
    "year": 2009,
    "rated": "TV-MA",
    "released": "Unknown",
    "duration": 120,
    "genre": ["Action", "Adventure" , "Fantasy"],
    "director": "Unknown",
    "plot": "Follow the cat",
    "language": "English",
    "poster": "http://ia.media-imdb.com/images/M/MV5BOTA4NTkzMjUzOF5BMl5BanBnXkFtZTgwNzg5ODkxOTE@._V1_SX300.jpg",
    "metascore": 0
}